### ISSUE TITLE
Unable to download latest space drain from github

### ISSUE THREAD

**Issue by MhulzR** [cloudfoundry/cf-drain-cli#17]
Hi,

I configured a space drain yesterday with no issue but today i'm facing this error : 
```
Downloading latest space drain from github...
unexpected status code (403) from github
```

I was able to uninstall and install again drains. I saw recent commit on space drain, don't know if that could be related to that.

Sorry if it's not related.
Thank you for your help.

**Comment by MasslessParticle** [comment]
The binary ought to be publicly available. Have you tried pulling down the latest binary with wget? 

We've seen this issue when github is rate-limiting us.

**Comment by jtuchscherer** [comment]
@MhulzR We are in the process of removing all `v2-` commands. They depend on the existence of the Reverse Log Proxy Gateway (RLP Gateway) in your CF installation. The RLP Gateway is a rather new feature. It is possible that it does not exist yet in your CF deployment.
