### ISSUE TITLE
UAA Refresh Token is only valid for 30 days by default

### ISSUE THREAD

**Issue by giner** [cloudfoundry/cf-drain-cli#21]
By default refresh token [expires in 30 days](https://github.com/starkandwayne/ultimate-guide-to-uaa/blob/master/docs/refresh-tokens.md#access-tokens-and-refresh-tokens), so the drain app will be failing on most installations after a while. Shouldn't this be documented or I'm missing something?

**Comment by chentom88** [comment]
You're right that the token periodically expires. To account for this, the space_drain app gets a new refresh token and restages itself when a CAPI request fails:

- https://github.com/cloudfoundry/cf-drain-cli/blob/b0cf825c053d660884aa517edb5c6a4c906f9810/cmd/space_drain/main.go#L39-L58

- https://github.com/cloudfoundry/cf-drain-cli/blob/b0cf825c053d660884aa517edb5c6a4c906f9810/internal/cloudcontroller/http_curl_client.go#L86-L95

- https://github.com/cloudfoundry/cf-drain-cli/blob/develop/internal/cloudcontroller/restager.go

**Comment by giner** [comment]
Hi @chentom88, I've just [asked](https://cloudfoundry.slack.com/archives/C03FXANBV/p1549581985075300) on Slack and UAA devs said that "refresh_token" is not refreshable. What else may I be missing?

**Comment by chentom88** [comment]
@giner The confusion may be stemming from the fact that we do not "refresh" the refresh token. When we get an authorization error, we make a completely new request to UAA to get a fresh set of access and refresh tokens

https://github.com/cloudfoundry/cf-drain-cli/blob/b0cf825c053d660884aa517edb5c6a4c906f9810/internal/cloudcontroller/http_curl_client.go#L86-L95

https://github.com/cloudfoundry/cf-drain-cli/blob/b0cf825c053d660884aa517edb5c6a4c906f9810/internal/cloudcontroller/http_curl_client.go#L104-L128

https://github.com/cloudfoundry/cf-drain-cli/blob/b0cf825c053d660884aa517edb5c6a4c906f9810/internal/cloudcontroller/token_manager.go#L43-L51

https://github.com/cloudfoundry-incubator/uaago/blob/master/client.go#L115-L131
