### ISSUE TITLE
Question about syslog url.

### ISSUE THREAD

**Issue by LYHuang** [cloudfoundry/cf-drain-cli#23]
Hello,

The syslog drain is working when I use the `syslog://some.server` url. But if I am using `https://another.server` as my log drain url, I can only see the `POST` request coming and didn't see any data in the `body`.

Is there any extra setting I need to do?

Thanks.

**Comment by kitemongerer** [comment]
@LYHuang How are you seeing the POST request come through?

**Comment by LYHuang** [comment]
@kitemongerer I realize that the coming data is the stream, and I can actually see some data drain to my `https` server now. However, the logs seems not consistent. In my https server, I can not see any syslog with type `APP/PROC/WEB/0`, but I can see that in my cloud foundry logs page and my syslog server.

**Comment by kitemongerer** [comment]
@LYHuang can you look at the `syslog_adapter.dropped` metric emitted by the syslog adapter. It may be that your http server is not consuming as fast as the TCP server and can't keep up

**Comment by LYHuang** [comment]
@kitemongerer Where can I find the `syslog_adapter.dropped`?

Also, here is the code I am using for receive logs.
```
server.post('/', (req, res, next) => {
    console.log('Syslog request: ' + id);
    req.on('data', (data) => {
        console.log(data.toString());
    }).on('close', () => {
        console.log('Disconnect: ' + id);
        res.send(200);
    });
    return next();
});
```
I notice that the `data` event for the `request` only get triggered once when the connection get established, is there any setup I need to do at the service?
