### ISSUE TITLE
the help syntax for create-drain is incorrect

### ISSUE THREAD

**Issue by randomtask1155** [cloudfoundry/cf-drain-cli#6]
```
python-hello-world-flask:> cf create-drain -type metrics "hello-world-flask" my-drain syslog-tls://my-server:1234
Invalid arguments, expected 2, got 3.
```

https://github.com/cloudfoundry/cf-drain-cli/blob/9475eb14537d21075e993b01e2072a003308175b/main.go#L72

does not allow you to specify `<drain-name>`

```
 create-drain [options] <app-name> <drain-name> <syslog-drain-url>
```

also create-drain is selected from arg 1 even though we define a flag for it. 

```
https://github.com/cloudfoundry/cf-drain-cli/blob/9475eb14537d21075e993b01e2072a003308175b/internal/command/create_drain.go#L34
```

**Comment by bradylove** [comment]
@randomtask1155 thank you for pointing this out. We had removed the requirement to provide a drain name and forgot to update the help text. This has been fixed.
